AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String
  AppKey:
    Type: String
  SecretKey:
    Type: String

Globals:
  Api:
    Cors: "'*'"
  Function:
    Runtime: nodejs8.10
    Handler: shared/kappa.handler
    Timeout: 180
    Environment:
      Variables:
        APP_ID: !Ref AppId
        APP_KEY: !Ref AppKey
        SECRET_KEY: !Ref SecretKey

Resources:

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/hello
      Events:
        ScheduleOneMinuteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  GetGameChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/getGameChannel
      Events:
        GetChannelEvent:
          Type: Api
          Properties:
            Path: /getgamechannel
            Method: get

  PusherAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/pusherAuth
      Events:
        pusherAuthEvent:
          Type: Api
          Properties:
            Path: /pusherauth
            Method: post